# Entries starting with _ are ignored and are used as shortcuts for the others
_ark: &ark
    appid: 376030
    config: config/config.ini

_sotf: &sotf
    appid: 445400
    config: config/config-445400.ini



sotf:
    <<: *sotf
    stages:
        - asb
        - wiki
    triggers:
        buildid: true
        frequency: P2D
    mods: []
    # maps: (allows all)


ark_core_fast:
    <<: *ark
    stages:
        - sanity.species
        - sanity.items
        - asb
        - wiki.items
        - wiki.species
        - wiki.drops
        - wiki.loot_crates
        - wiki.event_colors
    triggers:
        buildid: true
        # frequency: PT12H
    include_official_mods: true
    mods: []
    maps: []


ark_core_full:
    <<: *ark
    stages:
        - sanity
        - asb
        - wiki
    triggers:
        buildid: true
    include_official_mods: true
    mods: []
    # maps: (allows all)


ark_mods_12h:
    <<: *ark
    stages:
        - asb.species
        - wiki.species
        - wiki.items
    triggers:
        frequency: PT12H
    mods:
        - 1373744537 # AC2
        - 893735676 # AE
        - 1090809604 # Pyria
        - 1565015734 # BetterDinosTest
        - 1576299694 # ElementalDinos
        - 1652120435 # AtlasPort
        - 839162288 # Primal_Fear
        - 1125442531 # Gaia
        - 1734595558 # Pyria2
        - 1675895024 # NoUntameables
        - 1676159020 # Aquaria
        - 2135314513 # CI_Dinos


ark_mods_2d:
    <<: *ark
    stages:
        - asb.species
        - wiki.species
        - wiki.items
    triggers:
        frequency: P2D
    mods:
        - 1729386191 # BonusDinoMod
        - 2447186973 # ArkOmega
        - 1270181453 # AdditionalAberrantDinos
        - 1984129536 # MTSMod
        - 2112724006 # DarkArk
        - 1522327484 # Additions_Pack
        - 1169020368 # Trex
        - 1083349027 # SpeedyFlyers
        - 1984936918 # MarniiModsWildlife
        - 1300713111 # RareSightings
        - 1654255131 # AtlasImports
        - 1523045986 # Paranoia
        - 1356703358 # Primal_Fear_Noxious_Creatures
        - 1787443195 # ChasmAdditionalDinos
        - 909297874 # NorwegianVikings
        - 899987403 # Primal_Fear_Bosses
        - 1405944717 # Project_Evolution


ark_mods_7d:
    <<: *ark
    stages:
        - asb.species
        - wiki.species
        - wiki.items
    triggers:
        frequency: P7D
    mods:
        - 2000326197 # ExtraResources
        - 895711211 # ClassicFlyers
        - 729352919 # IndomRex
        - 1821554891 # PurloviaTEST
        - 1681125667 # Primal_Fear_EX
        - 1587391872 # FasterFlyers
        - 1696957410 # MarniimodsTest
        - 919470289 # SSFlyer
        - 2110243671 # GrandHunt
        - 1768499278 # BalancedJPE
        - 1449927867 # Phoenix
        - 1445395055 # Indominus
        - 1092784125 # Gryphons
        - 814833973 # Wyvern_Mating
        - 2019846325 # ApexMod
        - 2003934830 # Beasts
        - 1783616332 # IceWyvernMating


ark_mods_manual_only:
    # no auto trigger
    <<: *ark
    stages:
        - asb.species
        - wiki.species
        - wiki.items
    mods:
        - 1785800853 # Behavorial-Expansion
        - 1606708617 # MysteriousMysteries
        - 1590726079 # AutoHarvestAnky
        - 1498206270 # SmallDragon
        - 1270132511 # GiantGlowpets
        - 1178308359 # ShadDragon
        - 2117881804 # FiresFixes
        - 2034355411 # Roya
        - 1934081600 # SoloFarmAnky
        - 1912640902 # MagicShinehorn
        - 1908568783 # BarbaryLion
        - 1850732334 # ForestWyvern
        - 1850728241 # RoyalPhoenix
        - 1662691167 # Senior
        - 1633860796 # DE_Breedable_RockDrakes
        - 1420423699 # ARKaeologyDinos
        - 1206835819 # AncientEarthModCollection
        - 1136390783 # PhoenixBreeding
        - 1729512589 # Brachiosaurus
        - 1268749723 # ShadCore
        - 883957187 # WyvernWorld
        - 1824174926 # CarnoTLC
        - 1821112850 # Iguana
        - 1783308979 # AdditionalDinos_Valguero
        - 1188224480 # OgAlphas
        - 1139775728 # Confuciusornis

