sotf:
    appid: &sotf 445400
    config: config/config-445400.ini
    stages:
        - asb
        - wiki.items
        - wiki.species
        - wiki.drops
        - wiki.loot_crates
    triggers:
        buildid: true
        # frequency: P2D
    mods: []
    # maps: (allows all)


ark_core_fast:
    appid: &ark 376030
    config: config/config.ini
    stages:
        - sanity.species
        - sanity.items
        - asb
        - wiki.items
        - wiki.species
        - wiki.drops
        - wiki.loot_crates
        - wiki.event_colors
    triggers:
        buildid: true
        # frequency: PT12H
    include_official_mods: true
    mods: []
    maps: []
